title: "Andrea Burti — Software Engineer"
author: Andrea Burti
description: "Personal site powered by coffee and Jekyll."
url: "https://boozee.github.io"
baseurl: ""        # e.g., /repo-name for project pages
permalink: pretty
timezone: Europe/Rome

# GitHub Pages compatible plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Collections (if needed later)
collections:
  projects:
    output: true

# Build settings
markdown: kramdown
theme: null

# Defaults
defaults:
  - scope: {path: ""}
    values:
      layout: "default"

# Navigation (can be overridden in _data/navigation.yml)
nav:
  - title: Home
    url: "/"
  - title: CV
    url: "/cv/"
  - title: Skills
    url: "/skills/"
  - title: Projects
    url: "/projects/"
  - title: Hobbies
    url: "/hobbies/"

# Allow Sass to be used
sass:
  style: compressed