title: "Andrea Burti"
author: Andrea Burti
description: "Code for Humans"
url: "https://boozee.github.io"
baseurl: ""        # e.g., /repo-name for project pages
permalink: pretty
timezone: Europe/Rome

# GitHub Pages compatible plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata

# Collections (if needed later)
collections:
  projects:
    output: true

# Build settings
markdown: kramdown
theme: null

# Defaults
defaults:
  - scope: {path: ""}
    values:
      layout: "default"

# Allow Sass to be used
sass:
  style: compressed

# Version
version:
  major: 1
  minor: 1